# Generated by Django 4.2.2 on 2023-07-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('projects', '0005_alter_contributor_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(choices=[('BUG', 'bug'), ('TASK', 'task'), ('FEATURE', 'feature')], max_length=10)),
                ('state', models.CharField(choices=[('TODO', 'todo'), ('INWORK', 'in_work'), ('RELEASED', 'released')], default='TODO', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=2000)),
                ('priority', models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], default='LOW', max_length=10)),
                ('assigned_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_assigned_user', to='user.softdeskuser')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_author', to='user.softdeskuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
