# Generated by Django 4.2.2 on 2023-07-09 17:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_project_created_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(choices=[('BUG', 'bug'), ('TODO', 'todo'), ('FEATURE', 'feature')], max_length=10)),
                ('state', models.CharField(choices=[('INWORK', 'in_work'), ('RELEASED', 'released')], default='INWORK', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=2000)),
                ('priority', models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('assigned_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_assigned_user', to='projects.contributor')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_author', to='projects.contributor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
