# Generated by Django 4.2.2 on 2023-07-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_contributor_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
